### ISSUE TITLE
chat-spaceの挙動確認

### ISSUE THREAD

**Issue by MaruyamaNao** [MaruyamaNao/chat-space#14]
ipアドレス
18.178.159.19

**Comment by miyu-yamamoto** [comment]
丸山さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○ サイドバーに表示されるグループ名、最新のメッセージ文の下に余分な線が表示される**
**○ 投稿時間が「undefinde」と表示される**
**○ リロードすると投稿していたメッセージが全て消えてしまう**
**○ 自動更新がされない**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by MaruyamaNao** [comment]
修正しました

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
